In [1]:
pip install opencv-python


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\lenovo\anaconda3\python.exe -m pip install --upgrade pip' command.


In [2]:
import cv2

In [12]:
img=cv2.imread('E:/D Drive/Images/1.jpg')

In [7]:
print(type(img))

<class 'numpy.ndarray'>


In [13]:
print(img.shape)

(1944, 2592, 3)


In [14]:
cv2.imshow('Image_1',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
b=img[:,:,0]
cv2.imshow('Image_2',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
print(b)

[[78 79 80 ... 51 51 51]
 [78 79 80 ... 51 51 51]
 [77 78 79 ... 51 51 52]
 ...
 [ 5  5  6 ... 44 45 45]
 [ 5  5  5 ... 42 43 43]
 [ 6  5  4 ... 41 41 42]]


In [17]:
g=img[:,:,1]
r=img[:,:,2]
cv2.imshow('Blue',b)
cv2.imshow('Green',g)
cv2.imshow('Red',r)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
# Play Video in Python

import numpy as np
import cv2
cap=cv2.VideoCapture('D:/2.mp4')
if cap.isOpened()==False:
    print("Can't open video....")
    
while True:
    ret, frame=cap.read()
    
    if ret==True:
        cv2.imshow('Frame',frame)
        
        if cv2.waitKey(25) & 0xFF==27:
            break
    else:
        break
        
cap.release()
cv2.destroyAllWindows()