In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3]) #create a rank of 1 array
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.shape)

(3,)


In [8]:
b=np.array([[1,2,3],[5,6,7]]) #create a rank of  array
print(b.shape)

(2, 3)


In [9]:
b

array([[1, 2, 3],
       [5, 6, 7]])

Zeros in numpy

In [10]:
z=np.zeros((2,3))

In [11]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
o=np.ones((3,5))
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
f=np.full((2,2),7)

In [16]:
f

array([[7, 7],
       [7, 7]])

Create a 2X2 identity matrix using Numpy

In [19]:
d=np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
r=np.random.random((2,3))

In [23]:
r

array([[0.71633181, 0.58553978, 0.80201018],
       [0.59784194, 0.26222985, 0.5862286 ]])

In [24]:
p=np.array([[1,2,3],[5,6,7],[8,9,10]]) #create a rank of 3 array
p

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [27]:
l=p[1:3,1:3]
l

array([[ 6,  7],
       [ 9, 10]])

In [29]:
bool_id=(p>5)
bool_id

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [30]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [31]:
print(a+7)

[ 8  9 10]


In [32]:
print(b-a)

[3 3 3]


In [35]:
p=np.array([[1,2,3],[5,6,7],[8,9,10]]) #create a rank of 3 array
p


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [36]:
print(p.T)

[[ 1  5  8]
 [ 2  6  9]
 [ 3  7 10]]


In [37]:
a=np.array([1,2,3,5,6,8])

In [40]:
a=a.reshape(2,3)


In [41]:
a

array([[1, 2, 3],
       [5, 6, 8]])

In [42]:
p=np.array([[1,2,3],[5,6,7],[8,9,10]])

In [45]:
p=p.reshape(1,9)

In [46]:
p

array([[ 1,  2,  3,  5,  6,  7,  8,  9, 10]])